workspace 'pokedex'

target 'pokedex' do
  project 'pokedex.project'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pokedex

  target 'pokedexTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pokedexUITests' do
    # Pods for testing
  end

end

target 'CoreNetwork' do
  project 'CoreNetwork/CoreNetwork.project'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pokedex

  target 'CoreNetworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CoreNetworkProtocols' do
  project 'CoreNetworkProtocols/CoreNetworkProtocols.project'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pokedex

  target 'CoreNetworkProtocolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
