# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
workspace 'pokedex'

target 'pokedex' do
  project 'pokedex.project'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pokedex

  target 'pokedexTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pokedexUITests' do
    # Pods for testing
  end

end

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreNetwork' do
  project 'CoreNetwork/CoreNetwork.project'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pokedex

  target 'CoreNetworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
