workspace 'pokedex'

target 'pokedex' do
  project 'pokedex.project'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pokedex

  target 'pokedexTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pokedexUITests' do
    # Pods for testing
  end

end

target 'CoreNetwork' do
  project 'CoreNetwork/CoreNetwork.project'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreNetwork

  target 'CoreNetworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CoreNetworkProtocols' do
  project 'CoreNetworkProtocols/CoreNetworkProtocols.project'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreNetworkProtocols

  target 'CoreNetworkProtocolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PokemonInfo' do
  project 'PokemonInfo/PokemonInfo.project'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokemonInfo

  target 'PokemonInfoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PokemonPokedex' do
  project 'PokemonPokedex/PokemonPokedex.project'
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for PokemonPokedex

  target 'PokemonPokedexTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'UI' do
  project 'UI/UI.project'
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for UI

  target 'UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
